[platformio]
default_envs = esp32s3
src_dir = main

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = 
    -DEXTRA_COMPONENT_DIRS="../../components/touch;../../components/encoder;../../components/display/ssd1306;../../components/display/gc9a01;../../components/display/shared;../../components/i2c/pca9548a"
build_flags =
    -DTOUCH1_PIN=4
    -DTOUCH2_PIN=5
    -DENC1_CLK=6
    -DENC1_DT=7
    -DENC1_SW=15
    -DENC2_CLK=16
    -DENC2_DT=17
    -DENC2_SW=18 
    -DI2C_SDA=8 
    -DI2C_SCL=9
    -DSPI_MOSI=11
    -DSPI_SCK=12
    -DGC1_CS=38
    -DGC1_DC=39 
    -DGC1_RST=40
    -DGC2_CS=21
    -DGC2_DC=47 
    -DGC2_RST=48
    -DGC_BLK=3
 
[env:esp32s3]
board = esp32-s3-devkitc-1  
board_build.esp-idf.sdkconfig_append = path/to/sdkconfig.custom