[platformio]
default_envs = esp32d
src_dir = main

[env]
framework = espidf
monitor_speed = 115200

[env:esp32d]
platform = espressif32
board = esp32dev

[env:s3_wroom]
platform = espressif32
board = esp32-s3-devkitc-1

[env:s3_seeed]
platform = espressif32
board = seeed_xiao_esp32s3

[env:c6]
platform = espressif32
board = esp32-c6-devkitc-1