[platformio]
default_envs = esp32d
src_dir = main

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -DEXTRA_COMPONENT_DIRS="../../components;../../components/display;../../components/i2c;../../components/audio"



# ----------------------------------------------
# Pin definitions (change according to your wiring)
# ----------------------------------------------
build_flags = 
    -DBUTTON_PIN=4
    -DBUZZER_PIN=5
    -DRELAY_PIN=6
    -DRELAY_ACTIVE_LOW=1
    -DTOUCH_PIN=7
    -DVIBRATION_PIN=8
    -DPWM_DIMMER_PIN=9
    -DMOSFET_PIN=10
    -DENCODER_CLK=11
    -DENCODER_DT=12
    -DENCODER_SW=13
    -DI2C_SDA=21
    -DI2C_SCL=22
    -DSSD1306_ADDR=0x3C
    -DMAX98357_DIN=25
    -DMAX98357_BCLK=26
    -DMAX98357_LRC=27

[env:esp32d]
board = esp32dev

[env:s3_wroom]
board = esp32-s3-devkitc-1

[env:s3_seeed]
board = seeed_xiao_esp32s3

[env:c6]
board = esp32-c6-devkitc-1

[env:c6_seeed]
board = seeed_xiao_esp32c6