; =============================================================================
; SK6812 RGBW Strip Test
; =============================================================================

[platformio]
default_envs = esp32d
src_dir = main

[env]
framework = espidf
monitor_speed = 115200

[env:esp32d]
platform = espressif32
board = esp32dev
  